### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by antony-jr** [appimage-conan-community/conan-AppImageUpdaterBridge#1]
As the title implies, The latest version of the library has more bug fixes. Do I need to change this line(https://github.com/appimage-conan-community/conan-AppImageUpdaterBridge/blob/663239575855c73469a28733e317d33d3e2e9c31/conanfile.py#L6)  to update the package?

The latest version only deprecates some GUI classes but not the core library.  The core library received some serious fixes since **v1.0.4**

**CC**: @azubieta

**Comment by azubieta** [comment]
If there is a tag named `v1.0.4` and there are no new dependencies. Just create a new branch for that version and apply the change there. Then push it upstream.

**Comment by azubieta** [comment]
You have to update the version here too: https://github.com/appimage-conan-community/conan-AppImageUpdaterBridge/blob/663239575855c73469a28733e317d33d3e2e9c31/.travis.yml#L3

By the way I'm already building the new package. It will be available on the branch v1.1.2

**Comment by azubieta** [comment]
The build was completed successfully. Closing the issue as completed.

**Comment by azubieta** [comment]
Thanks for the new cool stuff :)
